[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#4E2A84"
backgroundColor="snow"
secondaryBackgroundColor="#B6ACD150"

[runner]
magicEnabled = true

[client]
toolbarMode = "minimal"
