[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4E2A84"
backgroundColor = "snow"
secondaryBackgroundColor = "#d2cddf"

[runner]
magicEnabled = true

[client]
toolbarMode = "auto"
